language: android

env:
  global:
    # Gradle sometimes takes too much memory, resulting in
    # memory pressure that fails the build. Reduce its initial
    # heap to help reduce issues.
    - GRADLE_OPTS="-Xms128m"

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-17

script: ./gradlew build lint findbugs test

after_failure:
- cat app/build/reports/findbugs/findbugs.html
- cat app/build/reports/tests/debug/index.html
- cat app/build/reports/tests/release/index.html
